# Generated by Django 6.1.1 on 2026-09-10 14:12

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix=''),
        ),
    ]
