# Generated by Django 6.1.1 on 2026-09-10 14:17

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='qa_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='question_answer_message',
            name='qam_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='', unique=True),
        ),
    ]
