# Generated by Django 6.1.1 on 2026-09-11 02:01

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartorder_oid_alter_cartorderitem_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix=''),
        ),
    ]
