# Generated by Django 6.1.1 on 2026-09-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cartorder_oid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='oid',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='oid',
            new_name='order_item_id',
        ),
    ]
