# Generated by Django 6.1.1 on 2026-09-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cartorderitem_coupons_cartorderitem_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='repy',
            new_name='reply',
        ),
    ]
