# Generated by Django 6.1.1 on 2026-09-26 08:41

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_repy_review_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course-file'),
        ),
    ]
