# Generated by Django 6.1.1 on 2026-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_course_id_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantitem',
            old_name='file',
            new_name='varient_file',
        ),
    ]
