# Generated by Django 6.1.1 on 2026-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=100, null=True),
        ),
    ]
